//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Locations = new HashSet<Location>();
            this.TroubleCodes = new HashSet<TroubleCode>();
        }
    
        public int Id { get; set; }
        public string CarManufacurer { get; set; }
        public string CarModel { get; set; }
        public int UserId { get; set; }
        public string CarNumber { get; set; }
        public string VINNumber { get; set; }
        public Nullable<decimal> FuelTankCapacity { get; set; }
        public Nullable<decimal> FuelConsumptionUrban { get; set; }
        public Nullable<decimal> FuelConsumptionExtraUrban { get; set; }
    
        public virtual BaseUser User { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<TroubleCode> TroubleCodes { get; set; }
    }
}
